config/routes.rb
Careli::Application.routes.draw do
  root :to => 'home#index'

  devise_for :users 

  devise_scope :user do
      get "sign_in", :to => "devise/sessions#new"
      get "sign_out", :to => "devise/sessions#destroy"
      get "sign_up", :to => "devise/registrations#new"
  end

  get 'contact' => 'home#contact'
  get 'about' => 'home#about'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def contact
  end

  def about 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.haml
.row
  .large-12.columns
    .page-content
      %h1 About us
      %p
        Occupy tumblr photo booth locavore squid. Hashtag asymmetrical narwhal, viral typewriter 
        swag lomo banjo tattooed lo-fi master cleanse salvia yr mlkshk whatever. Organic try-hard
        Cosby sweater gentrify, fingerstache scenester hoodie stumptown. Twee direct trade helvetica
        farm-to-table stumptown. Tofu lo-fi helvetica Banksy occupy forage swag brunch, bicycle rights 
        american apparel ugh artisan Odd Future kale chips aesthetic. Selfies keffiyeh american apparel.

app/views/home/contact.html.haml
.row
  .large-12.columns
    .page-content
      %h1 Contact us
      %p
        Pork belly Neutra thundercats, raw denim tumblr velit vegan pariatur ugh Schlitz direct trade literally kale chips Bushwick.
        Accusamus organic nisi consequat. Readymade fap ea, fashion axe commodo hoodie disrupt proident fixie Truffaut enim dolor
        salvia voluptate tattooed. Est odio direct trade nulla in. Voluptate officia skateboard duis enim Tonx. Consectetur meh selfies
        exercitation, vero mustache artisan leggings pour-over veniam tempor semiotics. Pickled Austin Banksy, consequat chambray deep.

app/views/home/index.html.haml
.row
  .large-12.columns
    %ul{"data-options" => "", "data-orbit" => ""}
      %li
        =image_tag('slider1.jpg')
      %li
        =image_tag('slider2.jpg')
      %li
        =image_tag('slider4.jpg')
%br

.row
  .large-12.columns
    .page-content
      .large-4.columns.parents-info
        =image_tag('kc_aboutus.jpg')
        %h4 About us 
        %p Bespoke scenester Portland Williamsburg 90's. 90's Tonx 8-bit, hashtag tousled biodiesel jean shorts vegan pug Bushwick Carles. Pug polaroid fanny pack, Echo Park semiotics McSweeney's thundercats ennui wayfarers intelligentsia trust fund post-ironic. Austin literally tattooed, roof party swag blue bottle fap. Freegan beard salvia, intelligentsia try-hard kitsch food truck ethnic. Master cleanse fingerstache kale chips post-ironic VHS helvetica.
      .large-4.columns.teachers-info
        =image_tag('dads_gnome.jpg')
        %h4 Services
        %p Deep v McSweeney's 90's put a bird on it kitsch voluptate. Austin tattooed officia aesthetic Bushwick nulla. Hashtag wayfarers lomo brunch Pinterest selvage. Squid quis in Banksy dolore consectetur. Et quis actually, pop-up mixtape sustainable tempor dolor. Fanny pack keffiyeh Tonx fap, fashion axe ethical officia. Ea laboris McSweeney's, DIY keytar in cornhole Godard.
      .large-4.columns.teachers-info
        =image_tag('dads_seabird.jpg')
        %h4 Contact Us
        %p High Life shabby chic mixtape, helvetica food truck Carles pork belly bespoke forage. Roof party farm-to-table quinoa, Pinterest twee tumblr single-origin coffee aesthetic actually vinyl pop-up next level PBR Etsy. Lomo fanny pack wolf asymmetrical letterpress. Cornhole leggings master cleanse McSweeney's kogi. Church-key fixie put a bird on it hashtag lomo, quinoa Cosby sweater roof party blog Wes Anderson. 90's cornhole lo-fi intelligentsia, american apparel hella butcher aesthetic iPhone bicycle rights.
%br
%br

app/views/layouts/_footer.html.haml
%footer.row
  .large-12.columns
    %hr/
    
  .large-6.columns
    %p © 2013 Careli International
  .large-6.columns
    %ul.inline-list.right
      -if current_user
        %li
          %a{:href => "/admin"} Admin
      -else
        %li
          %a{:href => "/"} Home
        %li
          %a{:href => "/about"} About
        %li
          %a{:href => "/contact"} Contact

app/views/layouts/_header.html.haml
%nav.top-bar
  %ul.title-area
    / Title Area
    %li.name
      %h1
        %a{:href => root_path} Careli Inc
    / Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        %span Menu
  %section.top-bar-section
    %ul.left
      -if current_user
        %li.divider
        %li.active
          %a{:href => "#"} Dashboard 
        %li.divider
        %li
          %a{:href => "#"} Logout
      -else
        %li.divider
        %li.active
          %a{:href => new_user_session_path} Sign In 
        %li.divider
        %li
          %a{:href => new_user_registration_path} Register 


      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Careli" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render :partial => 'layouts/header' %>
    <%= yield %>
    <%= render :partial => 'layouts/footer' %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>